    erDiagram
    USER ||--o{ FLIGHT_BOOKING : makes
    USER ||--o{ TROLLEY_BOOKING : makes

    USER {
        int id_user PK
        varchar user_name
        varchar password
    }

    PERSON ||--|| USER : register

    PERSON {
        int id_user PK, FK
        varchar name
        varchar last_names
        varchar curp
        date birth_date
        varchar email
    }

    %% -------- AIRPORT / FLIGHTS --------

    AIRPORT ||--o{ FLIGHT : origin
    AIRPORT ||--o{ FLIGHT : destination

    AIRPORT {
        int id_airport PK
        varchar city_name
        varchar airport_name
        varchar airport_code
    }

    FLIGHT {
        int id_flight PK
        varchar flight_number
        varchar flight_name
        int origin_airport_id FK
        int dest_airport_id FK
        varchar origin_city
        varchar destination_city
        date flight_date
        time departure_time
        time arrival_time
        decimal base_price
        enum status
    }

BOOKING_SEAT }o--||FLIGHT:seats_in
%% status (confirmed, pending, expired, cancelled)
BOOKING_SEAT{
     int id_seat PK
     int id_flight FK
     int id_booking FK
     varchar seat_number
     datetime expires_at
     datetime selected_at
     enum status 
}


    FLIGHT ||--o{ FLIGHT_BOOKING : booked_in

    FLIGHT_BOOKING {
        int id_booking PK
        int id_user FK
        int id_flight FK
        int number_of_seats
        datetime booking_date
        enum status
    }

    FLIGHT_BOOKING ||--|{ TICKET : generates

    TICKET {
        int id_ticket PK
        int id_booking FK
        datetime booking_date
        varchar passenger_full_name
        decimal ticket_price
    }

    %% -------- TROLLEY SYSTEM --------

    TROLLEY_MODEL ||--o{ TROLLEY: specifies

    TROLLEY_MODEL{
        int id_model PK
        int capacity
        varchar model_name
    }

    TROLLEY ||--o{ TROLLEY_TRIP : assigned_to

    TROLLEY {
        int id_trolley PK
        varchar plate_number
        int id_model FK
    }

    ROUTE ||--|{ ROUTE_STOP : contains
    ROUTE ||--o{ TROLLEY_ROUTE_SCHEDULE : has

    ROUTE {
        int id_route PK
        varchar route_name
    }

    %% BUS_STATION replaces TROLLEY_STOP
    BUS_STATION ||--o{ ROUTE_STOP : is_stop_in

    BUS_STATION {
        int id_station PK
        varchar city_name
        varchar station_name
        varchar station_code
        varchar adress
    }

    ROUTE_STOP {
        int id_route_stop PK
        int id_route FK
        int id_station FK
        int stop_order
    }

    %% -------- SCHEDULE --------

    TROLLEY_ROUTE_SCHEDULE ||--o{ SCHEDULE_DAY : occurs_on
    TROLLEY_ROUTE_SCHEDULE ||--o{ TROLLEY_TRIP : generates

    TROLLEY_ROUTE_SCHEDULE {
        int id_route_schedule PK
        int id_route FK
        time departure_time
        time arrival_time
    }

    SCHEDULE_DAY {
        int id_schedule_day PK
        int id_route_schedule FK
        enum day_of_week
    }

    %% -------- TRIPS & BOOKINGS --------

    TROLLEY_TRIP ||--o{ TROLLEY_BOOKING : reserved_in

    TROLLEY_TRIP {
        int id_trip PK
        int id_route_schedule FK
        int id_trolley FK
        int origin_station_id FK
        int dest_station_id FK
        date trip_date
        time departure_time
        time arrival_time
        decimal base_price
        enum status
    }

    TROLLEY_BOOKING ||--|{ TICKET : generates

    TROLLEY_BOOKING {
        int id_booking PK
        int id_user FK
        int id_trip FK
        int boarding_stop_id FK
        int alighting_stop_id FK
        int number_of_seats
        datetime booking_date
        enum status
    }
