erDiagram
    USER ||--o{ BOOKING : makes

%% A user can have many reservations
%% Many reservation are of the user
    USER {
        int id_user PK
        string email
        string user_name
        string password
    }
%% One PERSON can have a one user
   PERSON ||--|| USER  : register

    PERSON{
        int id_user PK,FK
        string NAME(S)
        string LAST_NAMES
        varchar CURP
        string birth_date
            }

   LOCATION ||--o{ FLIGHT : origin
    LOCATION||--o{ FLIGHT : destination

    LOCATION {
        int id_location PK
        string  city_name
        string  airport_name
        string  airport_code
    }
    
    FLIGHT ||--o{ BOOKING : included_in
%%int origin_id FK --> location.id_location -- departure place
 %%int origin_id FK --> location.id_location -- arrival place   
    FLIGHT {
        int id_flight PK
        varchar flight_name
        int origin_id FK
        int dest_id FK
     datetime departure_time
     datetime arrival_time
     int total_seats
     int base_prices
    }
    
    SEATS_RESERVATION }o--||FLIGHT:seats_in
%% satus (confirmed, pending, expired, cancelled)
SEATS_RESERVATION{
     int id_seat PK
     int id_flight FK
     int id_booking FK
     varchar seat_number
     string expires_at
     string selected_at
     int status 
}
    BOOKING ||--|{ TICKET : generates

    BOOKING {
        int id_booking PK
        int id_user FK
        int id_flight FK
        datetime date
        string status
    }

    TICKET {
        int id_ticket PK
        int id_booking FK
        string qr_code
    }

    TROLLEY ||--o{ TROLLEY_SCHEDULE : assigned_to

    TROLLEY {
        int id_trolley PK
        string plate_number
        int id_model FK
    }

    ROUTE ||--|{ ROUTE_STOP : contains

    ROUTE {
        int id_route PK
        string route_name
    }

    TROLLEY_STOP ||--o{ ROUTE_STOP : location

    TROLLEY_STOP {
        int id_stop PK
        string name
        string coordinates
    }

    ROUTE_STOP {
        int id_route FK
        int id_stop FK
        int stop_order
    }

    TROLLEY_SCHEDULE {
        int id_schedule PK
        int id_trolley FK
        int id_route FK
        datetime departure_time
    }
